<?php

namespace App\Exceptions;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Throwable;

class Handler extends ExceptionHandler {
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */


    public function register(): void {
        $this->renderable(function (NotFoundHttpException $e, Request $request) {
            $adminDir = config('app.configAdminDir');
            $adminDirLens = strlen($adminDir);
            $currentSlug = Route::current()->uri ;
            $currentSlug = str_replace('ar/'.$adminDir,$adminDir,$currentSlug);
            $currentSlug = str_replace('en/'.$adminDir,$adminDir,$currentSlug);
            if($e->getStatusCode() == 404 and mb_substr($currentSlug, 0, $adminDirLens) == $adminDir ){
                abort(410);
            }
        });
        $this->reportable(function (Throwable $e) {
            //
        });
    }


//    public function render($request, Throwable $e) {
//        if($e instanceof ModelNotFoundException){
//
//        }
//        return parent::render($request, $e); // TODO: Change the autogenerated stub
//    }
}
