-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 21, 2024 at 04:43 PM
-- Server version: 10.4.25-MariaDB
-- PHP Version: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `app_card`
--

--
-- Dumping data for table `app_card_input`
--

INSERT INTO `app_card_input` (`id`, `cat_id`, `vip`, `input_id`, `name_key`, `icon_i`, `url`, `url_user`, `regex`, `err_ar`, `err_en`, `type`, `input_dir`, `is_active`, `position`, `position_vip`) VALUES
(1, 1, 0, 'Address', 'field_address', 'fa-solid fa-map-marker-alt', NULL, NULL, NULL, '', '', 'text', 'ar', 0, '1', '0'),
(2, 1, 1, 'Email', 'field_email', 'fa-solid fa-envelope', NULL, NULL, NULL, '', '', 'email', 'en', 1, '4', '2'),
(3, 1, 1, 'Phone', 'field_phone', 'fa-solid fa-phone', NULL, NULL, '^\\+?\\d{7,25}$', 'يجب أن يكون رقم الهاتف بصيغة صحيحة مثل: +123456789', 'The phone number must be in a valid format like: +123456789', 'number', 'en', 1, '3', '3'),
(4, 1, 0, 'Web', 'field_web', 'fa-solid fa-globe', NULL, NULL, NULL, '', '', 'url', 'en', 1, '5', '0'),
(5, 1, 0, 'CompanyURL', 'field_company_url', 'fa-solid fa-globe', NULL, NULL, NULL, '', '', 'url', 'en', 1, '6', '0'),
(6, 1, 0, 'Link', 'field_link', 'fa-solid fa-link', NULL, NULL, NULL, '', '', 'url', 'en', 0, '7', '0'),
(7, 1, 0, 'GoogleMap', 'field_google_map', 'fa-solid fa-map', NULL, NULL, '^https:\\/\\/maps\\.app\\.goo\\.gl\\/[A-Za-z0-9]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://maps.app.goo.gl/ID', 'The URL must be a valid Google Maps link like: https://maps.app.goo.gl/ID', 'url', 'en', 1, '8', '0'),
(8, 1, 0, 'BlogURL', 'field_blog_url', 'fa-solid fa-blog', NULL, NULL, NULL, '', '', 'url', 'en', 1, '9', '0'),
(9, 1, 0, 'PortfolioURL', 'field_portfolio_url', 'fa-solid fa-briefcase', NULL, NULL, NULL, '', '', 'url', 'en', 0, '10', '0'),
(10, 1, 0, 'Country', 'field_country', 'fa-solid fa-flag', NULL, NULL, NULL, '', '', 'text', 'ar', 0, '12', '0'),
(11, 1, 0, 'City', 'field_city', 'fa-solid fa-city', NULL, NULL, NULL, '', '', 'text', 'ar', 0, '2', '0'),
(12, 1, 0, 'PostalCode', 'field_postal_code', 'fa-solid fa-mail-bulk', NULL, NULL, '/^[a-zA-Z0-9\\s\\-]{4,10}$/', 'الرمز البريدي يجب أن يكون بين 4 إلى 10 أحرف أو أرقام ويُمكن أن يحتوي على مسافات أو شرطات', 'The postal code must be between 4 to 10 characters long and may include spaces or dashes', 'number', 'en', 1, '11', '0'),
(13, 2, 0, 'Shopify', 'business_shopify', 'fa-solid fa-store', 'https://www.shopify.com/', NULL, '^https:\\/\\/[a-zA-Z0-9-]+\\.myshopify\\.com\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://storename.myshopify.com', 'The URL must be a valid Shopify link like: https://storename.myshopify.com', 'url', 'en', 1, '1', '0'),
(14, 2, 0, 'WooCommerce', 'business_woocommerce', 'fa-solid fa-shopping-cart', 'https://woocommerce.com/', NULL, '^https:\\/\\/[a-zA-Z0-9-]+\\.(woocommerce\\.com|yourdomain\\.com)\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://storename.woocommerce.com', 'The URL must be a valid WooCommerce link like: https://storename.woocommerce.com', 'url', 'en', 1, '2', '0'),
(15, 2, 0, 'AmazonStore', 'business_amazon_store', 'fa-solid fa-store-alt', 'https://www.amazon.com/', NULL, '^https:\\/\\/www\\.amazon\\.com\\/[a-zA-Z0-9\\/-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://www.amazon.com/user', 'The URL must be a valid Amazon Store link like: https://www.amazon.com/user', 'url', 'en', 1, '3', '0'),
(16, 2, 0, 'Zendesk', 'business_zendesk', 'fa-solid fa-headset', 'https://www.zendesk.com/', NULL, '^https:\\/\\/[a-zA-Z0-9_-]+\\.zendesk\\.com\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://yourdomain.zendesk.com', 'The URL must be a valid Zendesk link like: https://yourdomain.zendesk.com', 'url', 'en', 0, '4', '0'),
(17, 2, 0, 'Freshdesk', 'business_freshdesk', 'fa-solid fa-life-ring', 'https://freshdesk.com/', NULL, '^https:\\/\\/[a-zA-Z0-9_-]+\\.freshdesk\\.com\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://yourdomain.freshdesk.com', 'The URL must be a valid Freshdesk link like: https://yourdomain.freshdesk.com', 'url', 'en', 0, '5', '0'),
(18, 2, 0, 'LiveChat', 'business_livechat', 'fa-solid fa-comments', 'https://www.livechat.com/', NULL, '^https:\\/\\/[a-zA-Z0-9_-]+\\.livechat\\.com\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://yourdomain.livechat.com', 'The URL must be a valid LiveChat link like: https://yourdomain.livechat.com', 'url', 'en', 0, '6', '0'),
(19, 2, 0, 'GitHub', 'business_github', 'fa-brands fa-github', 'https://github.com/', NULL, '^https:\\/\\/github\\.com\\/[a-zA-Z0-9_-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://github.com/user', 'The URL must be in a valid format like: https://github.com/user', 'url', 'en', 1, '7', '0'),
(20, 2, 0, 'GitLab', 'business_gitlab', 'fa-brands fa-gitlab', 'https://gitlab.com/', NULL, '^https:\\/\\/gitlab\\.com\\/[a-zA-Z0-9_-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://gitlab.com/user', 'The URL must be in a valid format like: https://gitlab.com/user', 'url', 'en', 1, '8', '0'),
(21, 2, 0, 'Bitbucket', 'business_bitbucket', 'fa-brands fa-bitbucket', 'https://bitbucket.org/', NULL, '^https:\\\\/\\\\/bitbucket\\\\.org\\\\/[a-zA-Z0-9_-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://bitbucket.org/user', 'The URL must be in a valid format like: https://bitbucket.org/user', 'url', 'en', 0, '9', '0'),
(22, 2, 0, 'Calendly', 'business_calendly', 'fa-solid fa-calendar', 'https://calendly.com/', NULL, '^https:\\/\\/calendly\\.com\\/[a-zA-Z0-9_-]+\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://calendly.com/username', 'The URL must be a valid Calendly link like: https://calendly.com/username', 'url', 'en', 0, '10', '0'),
(23, 2, 0, 'Zoom', 'business_zoom', 'fa-solid fa-video', 'https://zoom.us/', NULL, '^https:\\/\\/(www\\.)?zoom\\.us\\/j\\/[0-9]{9,11}(\\?pwd=[a-zA-Z0-9]+)?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://zoom.us/j/1234567890 أو مع كلمة مرور مثل: https://zoom.us/j/1234567890?pwd=yourpassword', 'The URL must be a valid Zoom link like: https://zoom.us/j/1234567890 or with a password like: https://zoom.us/j/1234567890?pwd=yourpassword', 'url', 'en', 0, '11', '0'),
(24, 2, 0, 'GoogleMeet', 'business_google_meet', 'fa-solid fa-video', 'https://meet.google.com/', NULL, '^https:\\/\\/meet\\.google\\.com\\/[a-zA-Z0-9_-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://meet.google.com/abc-defg-hij', 'The URL must be a valid Google Meet link like: https://meet.google.com/abc-defg-hij', 'url', 'en', 0, '12', '0'),
(25, 2, 0, 'MicrosoftTeamsMeeting', 'business_microsoft_teams_meeting', 'fa-solid fa-video', 'https://www.microsoft.com/en/microsoft-teams/', NULL, '^https:\\/\\/(www\\.)?teams\\.microsoft\\.com\\/l\\/meetup-join\\/[a-zA-Z0-9_-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://teams.microsoft.com/l/meetup-join/abc-defg-hij', 'The URL must be a valid Microsoft Teams Meeting link like: https://teams.microsoft.com/l/meetup-join/abc-defg-hij', 'url', 'en', 0, '13', '0'),
(26, 2, 0, 'Trello', 'business_trello', 'fa-solid fa-columns', 'https://trello.com/', NULL, '^https:\\/\\/trello\\.com\\/[a-zA-Z0-9_\\/-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://trello.com/board/board-id', 'The URL must be a valid Trello link like: https://trello.com/board/board-id', 'url', 'en', 0, '14', '0'),
(27, 2, 0, 'Asana', 'business_asana', 'fa-solid fa-tasks', 'https://asana.com/', NULL, '^https:\\/\\/app\\.asana\\.com\\/[a-zA-Z0-9_\\/-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://app.asana.com/0/project-id', 'The URL must be a valid Asana link like: https://app.asana.com/0/project-id', 'url', 'en', 0, '15', '0'),
(28, 2, 0, 'GoogleDrive', 'business_google_drive', 'fa-solid fa-cloud', 'https://drive.google.com/', NULL, '^https:\\/\\/drive\\.google\\.com\\/[a-zA-Z0-9_\\/-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://drive.google.com/drive/folders/folder-id', 'The URL must be a valid Google Drive link like: https://drive.google.com/drive/folders/folder-id', 'url', 'en', 0, '17', '0'),
(29, 2, 0, 'Dropbox', 'business_dropbox', 'fa-solid fa-box', 'https://www.dropbox.com/', NULL, '^https:\\/\\/(www\\.)?dropbox\\.com\\/[a-zA-Z0-9_-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://www.dropbox.com/user', 'The URL must be a valid Dropbox link like: https://www.dropbox.com/user', 'url', 'en', 1, '16', '0'),
(30, 3, 1, 'Facebook', 'social_facebook', 'fa-brands fa-square-facebook', 'https://www.facebook.com/', NULL, '^https?:\\/\\/(www\\.)?facebook\\.com\\/[a-zA-Z0-9.]+\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://www.facebook.com/user', 'The URL must be in a valid format like: https://www.facebook.com/user', 'url', 'en', 1, '1', '4'),
(31, 3, 1, 'Twitter', 'social_twitter', 'fa-brands fa-square-twitter', 'https://www.twitter.com/', NULL, '^https?:\\/\\/(www\\.)?x\\.com\\/[a-zA-Z0-9_]+\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://x.com/user', 'The URL must be in a valid format like: https://x.com/user', 'url', 'en', 1, '2', '5'),
(32, 3, 1, 'LinkedIn', 'social_linkedin', 'fa-brands fa-linkedin', 'https://www.linkedin.com/', NULL, '^https?:\\/\\/(www\\.)?linkedin\\.com\\/(in|company)\\/[a-zA-Z0-9_-]+\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://www.linkedin.com/in/user', 'The URL must be in a valid format like: https://www.linkedin.com/in/user', 'url', 'en', 1, '3', '6'),
(33, 3, 1, 'Instagram', 'social_instagram', 'fa-brands fa-instagram', 'https://www.instagram.com/', NULL, '^https?:\\/\\/(www\\.)?instagram\\.com\\/[a-zA-Z0-9_.]+\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://www.instagram.com/user', 'The URL must be in a valid format like: https://www.instagram.com/user', 'url', 'en', 1, '4', '7'),
(34, 3, 0, 'YouTube', 'social_youtube', 'fa-brands fa-youtube', 'https://www.youtube.com/', NULL, '^https:\\/\\/(www\\.)?youtube\\.com\\/@([a-zA-Z0-9_]+)\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://www.youtube.com/c/username', 'The URL must be a valid YouTube link like: https://www.youtube.com/c/username', 'url', 'en', 1, '5', '0'),
(35, 3, 0, 'Pinterest', 'social_pinterest', 'fa-brands fa-pinterest', 'https://www.pinterest.com/', NULL, '^https:\\/\\/www\\.pinterest\\.com\\/[a-zA-Z0-9_\\/-]+\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://www.pinterest.com/username', 'The URL must be a valid Pinterest link like: https://www.pinterest.com/username', 'url', 'en', 1, '6', '0'),
(36, 3, 0, 'Snapchat', 'social_snapchat', 'fa-brands fa-snapchat', 'https://www.snapchat.com/', NULL, '^https:\\/\\/(www\\.)?snapchat\\.com\\/add\\/[a-zA-Z0-9._]+\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://www.snapchat.com/add/user', 'The URL must be in a valid format like: https://www.snapchat.com/add/user', 'url', 'en', 0, '7', '0'),
(37, 3, 0, 'TikTok', 'social_tiktok', 'fa-brands fa-tiktok', 'https://www.tiktok.com/', NULL, '^https:\\/\\/(www\\.)?tiktok\\.com\\/@?[a-zA-Z0-9._-]+\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://www.tiktok.com/@username', 'The URL must be a valid TikTok link like: https://www.tiktok.com/@username', 'url', 'en', 0, '8', '0'),
(38, 3, 0, 'Reddit', 'social_reddit', 'fa-brands fa-reddit', 'https://www.reddit.com/', NULL, '^https:\\/\\/www\\.reddit\\.com\\/user\\/[a-zA-Z0-9_-]+\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://www.reddit.com/user/username', 'The URL must be a valid Reddit link like: https://www.reddit.com/user/username', 'url', 'en', 0, '9', '0'),
(39, 3, 0, 'Vimeo', 'social_vimeo', 'fa-brands fa-vimeo', 'https://www.vimeo.com/', NULL, '^https:\\/\\/vimeo\\.com\\/[a-zA-Z0-9_-]+\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://vimeo.com/username', 'The URL must be a valid Vimeo link like: https://vimeo.com/username', 'url', 'en', 0, '10', '0'),
(40, 3, 0, 'Quora', 'social_quora', 'fa-brands fa-quora', 'https://www.quora.com/', NULL, '^https:\\/\\/www\\.quora\\.com\\/profile\\/[a-zA-Z0-9_-]+\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://www.quora.com/profile/username', 'The URL must be a valid Quora link like: https://www.quora.com/profile/username', 'url', 'en', 0, '11', '0'),
(41, 3, 0, 'Tumblr', 'social_tumblr', 'fa-brands fa-tumblr', 'https://www.tumblr.com/', NULL, '^https:\\/\\/[a-zA-Z0-9_-]+\\.tumblr\\.com\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://username.tumblr.com', 'The URL must be a valid Tumblr link like: https://username.tumblr.com', 'url', 'en', 0, '12', '0'),
(42, 3, 0, 'Twitch', 'social_twitch', 'fa-brands fa-twitch', 'https://www.twitch.tv/', NULL, '^https:\\/\\/www\\.twitch\\.tv\\/[a-zA-Z0-9_-]+\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://www.twitch.tv/username', 'The URL must be a valid Twitch link like: https://www.twitch.tv/username', 'url', 'en', 0, '13', '0'),
(43, 3, 0, 'Medium', 'social_medium', 'fa-brands fa-medium', 'https://www.medium.com/', NULL, '^https:\\/\\/medium\\.com\\/@[a-zA-Z0-9_-]+\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://medium.com/@username', 'The URL must be a valid Medium link like: https://medium.com/@username', 'url', 'en', 0, '14', '0'),
(44, 3, 0, 'Dribbble', 'social_dribbble', 'fa-brands fa-dribbble', 'https://www.dribbble.com/', NULL, '^https:\\/\\/dribbble\\.com\\/[a-zA-Z0-9_-]+\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://dribbble.com/username', 'The URL must be a valid Dribbble link like: https://dribbble.com/username', 'url', 'en', 0, '15', '0'),
(45, 3, 0, 'Behance', 'social_behance', 'fa-brands fa-behance', 'https://www.behance.net/', NULL, '^https:\\/\\/www\\.behance\\.net\\/[a-zA-Z0-9_-]+\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://www.behance.net/username', 'The URL must be a valid Behance link like: https://www.behance.net/username', 'url', 'en', 0, '17', '0'),
(46, 3, 0, 'Flickr', 'social_flickr', 'fa-brands fa-flickr', 'https://www.flickr.com/', NULL, '^https:\\/\\/(www\\.)?flickr\\.com\\/[a-zA-Z0-9@_-]+\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://www.flickr.com/photos/username', 'The URL must be a valid Flickr link like: https://www.flickr.com/photos/username', 'url', 'en', 0, '16', '0'),
(47, 4, 1, 'WhatsApp', 'messaging_whatsapp', 'fa-brands fa-whatsapp', 'https://www.whatsapp.com/', NULL, '^\\+(\\d{7,25})$', 'برجاء اضافة الرقم بالصيغة الدوليه حتى يتم تفعيل رابط الارسال مثل +20122167899', 'Please add the number in international format to activate the send link +20122156988', 'number', 'en', 1, '1', '1'),
(48, 4, 0, 'Telegram', 'messaging_telegram', 'fa-brands fa-telegram', 'https://telegram.org/', NULL, '^\\+(\\d{7,25})$', 'برجاء اضافة الرقم بالصيغة الدوليه حتى يتم تفعيل رابط الارسال مثل +20122167899', 'Please add the number in international format to activate the send link +20122156988', 'number', 'en', 1, '2', '0'),
(49, 4, 0, 'Messenger', 'messaging_messenger', 'fa-brands fa-facebook-messenger', 'https://www.messenger.com/', NULL, '^https:\\/\\/m\\.me\\/[a-zA-Z0-9._-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://m.me/username', 'The URL must be a valid Messenger link like: https://m.me/username', 'url', 'en', 1, '3', '0'),
(50, 4, 0, 'MicrosoftTeams', 'messaging_teams', 'fa-brands fa-microsoft', 'https://www.microsoft.com/en/microsoft-teams', NULL, '^https:\\/\\/(www\\.)?teams\\.microsoft\\.com\\/[a-zA-Z0-9_\\/?-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://teams.microsoft.com/meeting-id', 'The URL must be a valid Microsoft Teams link like: https://teams.microsoft.com/meeting-id', 'url', 'en', 0, '4', '0'),
(51, 4, 0, 'Viber', 'messaging_viber', 'fa-brands fa-viber', 'https://www.viber.com/', NULL, '^\\+(\\d{7,25})$', 'برجاء اضافة الرقم بالصيغة الدوليه حتى يتم تفعيل رابط الارسال مثل +20122167899', 'Please add the number in international format to activate the send link +20122156988', 'number', 'en', 1, '5', '0'),
(52, 4, 0, 'WeChat', 'messaging_wechat', 'fa-brands fa-weixin', 'https://www.wechat.com/', NULL, '^weixin:\\/\\/dl\\/chat\\?[a-zA-Z0-9_-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: weixin://dl/chat?username', 'The URL must be a valid WeChat link like: weixin://dl/chat?username', 'number', 'en', 0, '6', '0'),
(53, 4, 0, 'Line', 'messaging_line', 'fa-brands fa-line', 'https://line.me/', NULL, '^https:\\/\\/line\\.me\\/ti\\/p\\/[a-zA-Z0-9_-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://line.me/ti/p/username', 'The URL must be a valid Line link like: https://line.me/ti/p/username', 'url', 'en', 0, '7', '0'),
(54, 4, 0, 'Kik', 'messaging_kik', 'fa-solid fa-comment-dots', 'https://www.kik.com/', NULL, '^kik:\\/\\/[a-zA-Z0-9_-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: kik://username', 'The URL must be a valid Kik link like: kik://username', 'number', 'en', 0, '8', '0'),
(55, 4, 0, 'Signal', 'messaging_signal', 'fa-solid fa-signal', 'https://signal.org/', NULL, '^https:\\/\\/signal\\.me\\/#p\\/\\d{10,15}$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://signal.me/#p/1234567890', 'The URL must be a valid Signal link like: https://signal.me/#p/1234567890', 'url', 'en', 0, '10', '0'),
(56, 4, 0, 'Slack', 'messaging_slack', 'fa-brands fa-slack', 'https://slack.com/', NULL, '^https:\\/\\/[a-zA-Z0-9_-]+\\.slack\\.com\\/?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://yourworkspace.slack.com', 'The URL must be a valid Slack link like: https://yourworkspace.slack.com', 'url', 'en', 1, '9', '0'),
(57, 4, 0, 'Discord', 'messaging_discord', 'fa-brands fa-discord', 'https://discord.com/', NULL, '^https:\\/\\/discord\\.com\\/users\\/\\d{17,19}$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://discord.com/users/12345678901234567', 'The URL must be a valid Discord link like: https://discord.com/users/12345678901234567', 'url', 'en', 0, '11', '0'),
(58, 4, 0, 'Skype', 'messaging_skype', 'fa-brands fa-skype', 'https://www.skype.com/', NULL, '^skype:[a-zA-Z0-9._-]+(\\?chat)?$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: skype:username أو skype:username?chat', 'The URL must be a valid Skype link like: skype:username or skype:username?chat', 'number', 'en', 0, '12', '0'),
(59, 4, 0, 'GoogleChat', 'messaging_google_chat', 'fa-brands fa-google', 'https://chat.google.com/', NULL, '^https:\\/\\/chat\\.google\\.com\\/[a-zA-Z0-9_\\/-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://chat.google.com/room-id', 'The URL must be a valid Google Chat link like: https://chat.google.com/room-id', 'url', 'en', 0, '13', '0'),
(60, 4, 0, 'SnapchatChat', 'messaging_snapchat', 'fa-brands fa-snapchat', 'https://www.snapchat.com/', NULL, '^https:\\/\\/www\\.snapchat\\.com\\/add\\/[a-zA-Z0-9._-]+$', 'يجب أن يكون الرابط بصيغة صحيحة مثل: https://www.snapchat.com/add/username', 'The URL must be a valid Snapchat Chat link like: https://www.snapchat.com/add/username', 'url', 'en', 1, '14', '0');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
